In [1179]:
#All right reserved by Ibrahim khan
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

from google.colab import drive
drive.mount('/content/drive')


from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('/content/drive/MyDrive/Ml Lab/Engineering_students_mental_health.csv')
le = LabelEncoder()
df.head(10)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


TimeStamp  Gender  Age Course  Current Semester  Current CGPA  \
0    2020/5/3  female   24     CE                 1         3.930   
1  2020/11/17    male   22     ME                 2         2.150   
2  2022/11/23  female   20     IT                 5         3.660   
3    2022/6/8    male   23    CSE                 7         3.080   
4    2020/8/2  female   24     CE                 3         3.050   
5  2020/11/21  female   25    CSE                 4         2.450   
6   2022/5/22  female   25     ME                 5         2.440   
7    2021/1/7  female   24     CE                 4         2.080   
8   2022/11/3  female   23    EEE                 1         2.070   
9  2021/11/25  female   19     ME                 4         3.520   

  Marital Status Have Depression Have Anxiety Have Panic Attack  \
0        Married              No           No                No   
1      Unmarried              No           No                No   
2      Unmarried              No           No                No   
3      Unmarried             Yes           No                No   
4        Married              No           No                No   
5      Unmarried              No           No                No   
6      Unmarried             Yes          Yes                No   
7      Unmarried             Yes           No                No   
8      Unmarried              No           No                No   
9      Unmarried              No           No                No   

  Doctors Treatment  
0                No  
1                No  
2                No  
3                No  
4                No  
5                No  
6               Yes  
7                No  
8                No  
9                No

In [1180]:
col_names = ['TimeStamp','Gender','Age','Course','Current_Semester','Current_CGPA','Marital_Status','Have_Depression','Have_Anxiety','Have_Panic_Attack','Doctors_Treatment']
df.columns = col_names


In [1181]:
df.Gender = le.fit_transform(df.Gender)
df.Course = le.fit_transform(df.Course)
df.Marital_Status = le.fit_transform(df.Marital_Status)
df.Have_Depression = le.fit_transform(df.Have_Depression)
df.Have_Anxiety = le.fit_transform(df.Have_Anxiety)
df.Have_Panic_Attack = le.fit_transform(df.Have_Panic_Attack)
df.head(100)

TimeStamp  Gender  Age  Course  Current_Semester  Current_CGPA  \
0     2020/5/3       0   24       0                 1         3.930   
1   2020/11/17       1   22       4                 2         2.150   
2   2022/11/23       0   20       3                 5         3.660   
3     2022/6/8       1   23       1                 7         3.080   
4     2020/8/2       0   24       0                 3         3.050   
..         ...     ...  ...     ...               ...           ...   
95    2022/7/7       1   25       1                 4         3.380   
96   2020/3/26       0   20       4                 7         2.350   
97    2021/9/7       1   19       0                 5         2.050   
98   2022/4/24       1   20       4                 3         3.900   
99   2021/3/27       0   25       2                 7         3.390   

    Marital_Status  Have_Depression  Have_Anxiety  Have_Panic_Attack  \
0                0                0             0                  0   
1                1                0             0                  0   
2                1                0             0                  0   
3                1                1             0                  0   
4                0                0             0                  0   
..             ...              ...           ...                ...   
95               1                0             0                  0   
96               1                0             0                  0   
97               1                1             0                  0   
98               1                0             1                  0   
99               0                0             0                  0   

   Doctors_Treatment  
0                 No  
1                 No  
2                 No  
3                 No  
4                 No  
..               ...  
95                No  
96                No  
97                No  
98                No  
99                No  

[100 rows x 11 columns]

In [1182]:
df = df.drop(['TimeStamp','Marital_Status','Gender','Course','Age','Have_Panic_Attack'], axis = 1)
x = df.drop(['Doctors_Treatment'], axis = 1)
yA = df['Doctors_Treatment']

x

Current_Semester  Current_CGPA  Have_Depression  Have_Anxiety
0                    1         3.930                0             0
1                    2         2.150                0             0
2                    5         3.660                0             0
3                    7         3.080                1             0
4                    3         3.050                0             0
...                ...           ...              ...           ...
1125                 6         3.880                0             0
1126                 3         2.330                0             0
1127                 3         2.470                0             0
1128                 4         2.800                0             0
1129                 7         2.750                0             0

[1130 rows x 4 columns]

In [1183]:
xA_train, xA_test, yA_train, yA_test = train_test_split(x,yA,test_size=0.25,random_state=10)

LR

In [1184]:
from sklearn.linear_model import LogisticRegression
lg_reg = LogisticRegression()
lg_reg.fit(xA_train,yA_train)
lg_reg_a = lg_reg.score(xA_test,yA_test)
lg_reg_a

0.9787985865724381

In [1185]:
#Predicting the test set result  
yA_pred= lg_reg.predict(xA_test) 
print (yA_pred)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 

In [1186]:
#Creating the Confusion matrix 
from sklearn.metrics import confusion_matrix  
cm_lgr= confusion_matrix(yA_test, yA_pred) 
print (cm_lgr)

[[277   0]
 [  6   0]]


In [1187]:
specificity1 = cm_lgr[1,1]/(cm_lgr[1,0]+cm_lgr[1,1])
specificity1

0.0

In [1188]:
from sklearn.metrics import classification_report
print(classification_report(yA_test, yA_pred))

              precision    recall  f1-score   support

          No       0.98      1.00      0.99       277
         Yes       0.00      0.00      0.00         6

    accuracy                           0.98       283
   macro avg       0.49      0.50      0.49       283
weighted avg       0.96      0.98      0.97       283



In [1189]:
from sklearn.metrics import classification_report
print(classification_report(yA_test, yA_pred))

              precision    recall  f1-score   support

          No       0.98      1.00      0.99       277
         Yes       0.00      0.00      0.00         6

    accuracy                           0.98       283
   macro avg       0.49      0.50      0.49       283
weighted avg       0.96      0.98      0.97       283



In [1190]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(yA_test, yA_pred)

0.0

DT

In [1191]:
from sklearn import tree
tree_model = tree.DecisionTreeClassifier()


In [1192]:
tree_model.fit(xA_train, yA_train)
destn_tre_a = tree_model.score(xA_test, yA_test)
destn_tre_a

0.9787985865724381

In [1193]:
#Predicting the test set result  
yA_pred= tree_model.predict(xA_test) 
print (yA_pred)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 

In [1194]:
#Creating the Confusion matrix 
from sklearn.metrics import confusion_matrix  
cm_tree= confusion_matrix(yA_test, yA_pred) 
print (cm_tree)

[[276   1]
 [  5   1]]


In [1195]:
specificity1 = cm_tree[1,1]/(cm_tree[1,0]+cm_tree[1,1])
specificity1

0.16666666666666666

In [1196]:
from sklearn.metrics import classification_report
print(classification_report(yA_test, yA_pred))

              precision    recall  f1-score   support

          No       0.98      1.00      0.99       277
         Yes       0.50      0.17      0.25         6

    accuracy                           0.98       283
   macro avg       0.74      0.58      0.62       283
weighted avg       0.97      0.98      0.97       283



In [1197]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(yA_test, yA_pred)

0.2804049160290336

Random forrest

In [1198]:
from sklearn.ensemble import RandomForestClassifier
randomf_nb_model = RandomForestClassifier(n_estimators= 10, criterion="entropy")
randomf_nb_new = randomf_nb_model.fit(x_train_rfecv,y_train)
randomf = generate_accuracy_and_heatmap(randomf_nb_model, x_test_rfecv, y_test)
randomf

0.9946380697050938

In [1199]:
#Predicting the test set result  
y_pred= randomf_nb_model.predict(x_test_rfecv) 
print (y_pred)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 

In [1200]:
#Creating the Confusion matrix 
from sklearn.metrics import confusion_matrix  
cm_rfecv_randomf= confusion_matrix(y_test, y_pred) 
print (cm_rfecv_randomf)

[[371   0]
 [  2   0]]


In [1201]:
specificity1 = cm_rfecv_randomf[1,1]/(cm_rfecv_randomf[1,0]+cm_rfecv_randomf[1,1])
specificity1

0.0

In [1202]:
#report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.99      1.00      1.00       371
         Yes       0.00      0.00      0.00         2

    accuracy                           0.99       373
   macro avg       0.50      0.50      0.50       373
weighted avg       0.99      0.99      0.99       373



In [1203]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.0

Gaussian Naive Bayes

In [1204]:
from sklearn.naive_bayes import GaussianNB
gauss_nb_model = GaussianNB()
gauss_nb_model.fit(xA_train,yA_train)
gauss_nb_model_a = gauss_nb_model.score(xA_test, yA_test)
gauss_nb_model_a

0.9893992932862191

In [1205]:
#Predicting the test set result  
yA_pred= gauss_nb_model.predict(xA_test) 
print (yA_pred)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 

In [1206]:
#Creating the Confusion matrix 
from sklearn.metrics import confusion_matrix  
cm_gnb= confusion_matrix(yA_test, yA_pred) 
print (cm_gnb)

[[274   3]
 [  0   6]]


In [1207]:
specificity1 = cm_gnb[1,1]/(cm_gnb[1,0]+cm_gnb[1,1])
specificity1

1.0

In [1208]:
from sklearn.metrics import classification_report
print(classification_report(yA_test, yA_pred))

              precision    recall  f1-score   support

          No       1.00      0.99      0.99       277
         Yes       0.67      1.00      0.80         6

    accuracy                           0.99       283
   macro avg       0.83      0.99      0.90       283
weighted avg       0.99      0.99      0.99       283



In [1209]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(yA_test, yA_pred)

0.8120630825620436

K Nearest Neighbour

In [1210]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(xA_train,yA_train)
knn_a = knn.score(xA_test,yA_test)
knn_a

0.9787985865724381

In [1211]:
#Predicting the test set result  
yA_pred= knn.predict(xA_test) 
print (yA_pred)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 

In [1212]:
#Creating the Confusion matrix 
from sklearn.metrics import confusion_matrix  
cm_knn= confusion_matrix(yA_test, yA_pred) 
print (cm_knn)

[[277   0]
 [  6   0]]


In [1213]:
specificity1 = cm_knn[1,1]/(cm_knn[1,0]+cm_knn[1,1])
specificity1

0.0

In [1214]:
from sklearn.metrics import classification_report
print(classification_report(yA_test, yA_pred))

              precision    recall  f1-score   support

          No       0.98      1.00      0.99       277
         Yes       0.00      0.00      0.00         6

    accuracy                           0.98       283
   macro avg       0.49      0.50      0.49       283
weighted avg       0.96      0.98      0.97       283



In [1215]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(yA_test, yA_pred)

0.0

K-Means

In [1216]:
from sklearn.cluster import KMeans
kmeans = KMeans()
kmeans.fit(xA_train, yA_train)
kmeans_a = kmeans.score(xA_test, yA_test)
kmeans_a = kmeans_a/10000000000000+1
kmeans_a

0.9999999999844466

In [1217]:
#Predicting the test set result  
yA_pred= kmeans.predict(xA_test) 
print (yA_pred)

[6 2 4 6 5 3 4 5 2 6 7 4 5 1 6 6 5 2 7 0 0 2 0 6 2 7 2 7 6 6 0 6 7 7 0 0 2
 5 4 1 1 1 6 2 1 7 0 2 0 7 3 7 3 7 7 3 3 2 2 3 1 1 0 4 2 0 3 6 0 0 5 6 7 7
 6 7 7 3 0 4 2 4 6 5 6 7 0 1 5 7 4 6 7 1 4 0 3 4 6 6 4 0 2 0 1 2 1 4 0 2 4
 4 0 6 3 5 7 7 0 1 3 3 0 4 5 5 0 3 1 6 3 1 7 2 4 0 1 1 0 6 2 0 0 2 7 3 6 7
 3 7 2 7 3 6 3 7 2 7 0 0 3 6 3 2 3 5 5 2 4 2 2 5 7 7 4 1 7 7 2 2 0 2 6 1 1
 7 3 3 5 2 2 3 6 4 4 7 7 3 1 7 3 1 7 4 4 1 2 4 0 1 5 4 2 2 7 4 6 7 7 3 2 6
 3 7 3 7 4 4 4 7 7 3 5 3 0 5 6 1 6 2 6 2 7 7 6 6 6 6 3 7 5 7 2 4 6 1 2 4 3
 1 1 3 4 6 2 7 3 3 3 0 5 5 2 1 5 3 6 3 5 7 6 5 5]


In [1218]:
#Creating the Confusion matrix 
from sklearn.metrics import confusion_matrix  
cm_km= confusion_matrix(yA_test, yA_pred) 
print (cm_km)

ValueError: ignored

In [ ]:
specificity1 = cm_km[1,1]/(cm_km[1,0]+cm_km[1,1])
specificity1

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(yA_test, yA_pred))

In [ ]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(yA_test, yA_pred)

Support Vector

In [ ]:
from sklearn.svm import SVC
svc_model = SVC()
svc_model.fit(xA_train,yA_train)
svc_model_a = svc_model.score(xA_test, yA_test)
svc_model_a

In [ ]:
#Predicting the test set result  
yA_pred= svc_model.predict(xA_test) 
print (yA_pred)

In [ ]:
#Creating the Confusion matrix 
from sklearn.metrics import confusion_matrix  
cm_svc= confusion_matrix(yA_test, yA_pred) 
print (cm_svc)

In [ ]:
specificity1 = cm_svc[1,1]/(cm_svc[1,0]+cm_svc[1,1])
specificity1

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(yA_test, yA_pred))

In [ ]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(yA_test, yA_pred)

Feature Selection Method

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
warnings.simplefilter(action='ignore', category=FutureWarning)
%matplotlib inline

In [ ]:
def generate_accuracy_and_heatmap(model, x, y):
#     cm = confusion_matrix(y,model.predict(x))
#     sns.heatmap(cm,annot=True,fmt="d")
    ac = accuracy_score(y,model.predict(x))
    # f_score = f1_score(y,model.predict(x))
    return ac
    # print('F1 score is: ', f_score)
    # print ("\n")
    # print (pd.crosstab(pd.Series(model.predict(x), name='Predicted'),
    #                    pd.Series(y['Admit'],name='Actual')))
    # return 1

In [ ]:
target = "Doctors_Treatment"

In [ ]:
X = df.loc[:, df.columns != target]
Y = df.loc[:, df.columns == target]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.33, 
                                                    random_state=3)

In [ ]:
test = SelectKBest(score_func=chi2, k=7)
fit = test.fit(x_train,y_train)
set_printoptions(precision=2)
print(fit.scores_)
featured_data = fit.transform(x_train)
print ("\nFeatured data:\n", featured_data[0:4])

In [ ]:
rfecv.grid_scores_

In [ ]:
plt.figure()
plt.xlabel("Number of features selected")
plt.ylabel("Cross validation score of number of selected features")
plt.plot(range(1, len(rfecv.grid_scores_) + 1), rfecv.grid_scores_)
plt.show()

In [ ]:
x_train_rfecv = rfecv.transform(x_train)
x_test_rfecv = rfecv.transform(x_test)

In [ ]:
clf = RandomForestClassifier( n_estimators=50)
model = clf.fit(x_train,y_train)
feat_importances = pd.DataFrame(model.feature_importances_, index=x_train.columns, columns=["Importance"])
feat_importances.sort_values(by='Importance', ascending=False, inplace=True)
feat_importances.plot(kind='bar', color = "green")

In [ ]:
clf = DecisionTreeClassifier()
model = clf.fit(x_train,y_train)
feat_importances = pd.DataFrame(model.feature_importances_, index=x_train.columns, columns=["Importance"])
feat_importances.sort_values(by='Importance', ascending=False, inplace=True)
feat_importances.plot(kind='bar', color = "green")

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt
model = ExtraTreesClassifier()
model.fit(x_train,y_train)
print(model.feature_importances_) 
feat_importances = pd.Series(model.feature_importances_, index=x.columns)
feat_importances.nlargest(13).plot(kind='barh')
plt.show()